(define #%helix-component-module (#%module "helix/components"))

(define (register-values module values)
  (map (lambda (ident) (#%module-add module (symbol->string ident) void)) values))
(register-values #%helix-component-module '(theme-scope-ref
key-event-right?
key-event-tab?
key-event-down?
key-event-enter?
Color/LightRed
UnderlineStyle?
Color/LightMagenta
style-with-reversed
Color/Green
Color-red
buffer/clear-with
style-with-rapid-blink
position-row
set-position-row!
Color?
set-style-bg!
Color/Magenta
style-underline-style
key-event-delete?
key-event-end?
theme->fg
key-event-pause?
key-event-up?
native-component-required-size
style-with-crossed-out
event-result/close
theme-scope
buffer/clear
key-event-keypad-begin?
Rect?
event-result/ignore-and-close
Color/Black
style-underline-color
Color/Gray
Color-blue
Underline/Reset
async-read-line
Style?
overlaid
Color/Blue
Color/LightYellow
set-style-fg!
focus-lost-event?
style->bg
key-event-caps-lock?
style-fg
paste-event-string
key-event?
key-modifier-alt
key-event-modifier
key-modifier-super
key-event-null?
Color/Cyan
key-event-page-down?
buffer-area
frame-set-string!
widget/list
Underline/Line
event-result/consume-without-rerender
on-key-event-char
area-width
key-event-insert?
Color/White
area-height
event-mouse-col
Underline/Dotted
style-bg
style
Buffer?
set-position-col!
event-result/ignore
Color/Indexed
string->key-event
key-modifier-ctrl
key-event-num-lock?
make-async-reader-writer
key-event-print-screen?
style-with-dim
Event?
style-with-bold
style-with-italics
key-event-char
key-event-home?
Color/LightCyan
Position?
position
style->fg
key-event-menu?
set-color-rgb!
Underline/Curl
key-event-F?
paste-event?
Color/rgb
event->key-event
Underline/DoubleLine
area-x
render-native-component
mouse-event?
key-event-left?
focus-gained-event?
Color/Reset
markdown-component
Color/LightGray
Color-green
event-mouse-kind
widget/list/render
key-event-backspace?
block/render
Color/Red
SteelEventResult?
style-with-hidden
Underline/Dashed
mouse-event-within-area?
event-result/consume
theme->bg
block
style-with-slow-blink
position-col
Color/LightGreen
new-component!
area
area-y
make-block
Color/LightBlue
key-event-page-up?
set-color-indexed!
Color/Yellow
key-event-scroll-lock?
key-modifier-shift
event-mouse-row
key-event-escape?
Widget/list?
))