(define #%helix-configuration-module (#%module "helix/core/configuration"))

(define (register-values module values)
  (map (lambda (ident) (#%module-add module (symbol->string ident) void)) values))
(register-values #%helix-configuration-module '(auto-completion
fp-git-global
raw-soft-wrap
cursorcolumn
preview-completion-insert
auto-info
#%raw-cursor-shape
undercurl
auto-pairs
lsp
update-language-config!
smart-tab
fp-ignore
ws-render
set-option!
jump-label-alphabet
terminal
sw-enable
register-whitespace
ig-character
raw-whitespace
inline-diagnostics-cursor-line-disable
ws-visible
scroll_lines
inline-diagnostics-other-lines-disable
set-lsp-config!
auto-pairs-default
sw-wrap-at-text-width
true-color
color-modes
ig-skip-levels
fp-git-ignore
update-configuration!
idle-timeout
insert-final-newline
rulers
inline-diagnostics-prefix-len
bufferline
fp-parents
refresh-all-language-configs!
rainbow-brackets
#%editor-auto-pairs
shell
inline-diagnostics-cursor-line-enable
inline-diagnostics-end-of-line-disable
register-lsp-notification-handler
raw-cursor-shape-set!
fp-follow-symlinks
completion-replace
gutters
get-keybindings
search
auto-save-default
inline-diagnostics-max-diagnostics
get-config-option-value
inline-diagnostics-max-wrap
raw-indent-guides
get-language-config
completion-trigger-len
#%update-configuration
register-indent-guides
raw-cursor-shape
fp-git-exclude
fp-hidden
raw-file-picker
set-language-config!
line-number
keybindings
register-lsp-call-handler
sw-max-indent-retain
inline-diagnostics-end-of-line-enable
scrolloff
text-width
cursorline
completion-timeout
inline-diagnostics-min-diagnostics-width
register-soft-wrap
ig-render
auto-format
ws-chars
workspace-lsp-roots
auto-pairs-map
statusline
inline-diagnostics-other-lines-enable
default-line-ending
set-configuration-for-file!
get-lsp-config
register-file-picker
sw-max-wrap
auto-save-after-delay-enable
set-keybindings!
auto-save
fp-max-depth
fp-deduplicate-links
sw-wrap-indicator
middle-click-paste
mouse
))