(define #%helix-typed-module (#%module "helix/core/typable"))

(define (register-values module values)
  (map (lambda (ident) (#%module-add module (symbol->string ident) void)) values))
(register-values #%helix-typed-module '(tree-sitter-highlight-name
buffer-close!
vsplit-new
earlier
reflow
set-language
update
get-option
buffer-close
reload
show-directory
hsplit-new
toggle-option
buffer-close-others
exit!
write-buffer-close!
debug-eval
log-open
pipe
move
redraw
write!
character-info
pipe-to
echo
change-current-directory
clipboard-yank
vsplit
hsplit
tree-sitter-subtree
primary-clipboard-paste-replace
run-shell-command
clear-register
later
reset-diff-change
format
sort
lsp-stop
lsp-restart
quit-all
lsp-workspace-command
exit
theme
write-buffer-close
primary-clipboard-yank-join
cquit
clipboard-paste-before
set-option
new
encoding
buffer-close-all
write-quit!
noop
tree-sitter-scopes
read
write-quit
primary-clipboard-yank
append-output
write-quit-all
clipboard-paste-after
buffer-previous
show-clipboard-provider
tree-sitter-layers
goto
insert-output
tutor
primary-clipboard-paste-after
write-all
buffer-close-others!
debug-remote
debug-start
goto-line
line-ending
clipboard-paste-replace
config-open
write-quit-all!
config-reload
clipboard-yank-join
quit
quit-all!
indent-style
write-all!
quit!
yank-join
primary-clipboard-paste-before
buffer-next
buffer-close-all!
config-open-workspace
open
yank-diagnostic
goto-column
write
reload-all
cquit!
))