[opener]
helix = [
  { run = 'tmux select-pane -L && tmux send-keys ":o $0" Enter', desc = "Insert file path in Helix buffer and close Yazi in floating pane" },
]

[open]
rules = [{ name = "**/*", use = "helix" }]
